# Generated by Django 3.1.5 on 2021-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210116_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_query_name='tags', to='shop.Tags'),
        ),
    ]
